<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ERP.IntegrationTests</AssemblyName>
    <RootNamespace>ERP.IntegrationTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\ERP.Domain\ERP.Domain.csproj" />
    <ProjectReference Include="..\..\src\Core\ERP.Application\ERP.Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\ERP.Persistence\ERP.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\ERP.Security\ERP.Security.csproj" />
    <ProjectReference Include="..\..\src\Shared\ERP.Shared\ERP.Shared.csproj" />
  </ItemGroup>

</Project>
